server:
  port: 8080

spring:
  application:
    name: book
  datasource:
    url: jdbc:mysql://localhost:8889/leaguespring
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true